First

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -7,6 +7,12 @@ COPY . .
 RUN npm install
 RUN npm run build
 
+# FAIL SAFE CHECK
+RUN if [ ! -d "dist" ]; then \
+      echo "Build failed: dist missing"; \
+      exit 1; \
+    fi
+
 RUN npm install -g serve
 
 CMD ["serve", "-s", "dist", "-l", "80"]
